// Generated by CrawlerBuild from decoded source assets.
namespace ForestCrawler;
internal static class AudioTiming {
internal const float Voice = 2.904f;
internal const float Scream = 7.56f;
internal const float Whisper = 16.176f;
internal const float Woo = 14.2628574f;
internal const float Reveal = 1.6500001f;
}
