using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;
using UnityEngine.Rendering;

public static class CrawlerBuild
{
    private const string Folder = "Assets/Crawler/";
    public static void Build()
    {
        if (Application.unityVersion != "6000.0.75f1") throw new InvalidOperationException("Build with Unity 6000.0.75f1 to match the installed game.");
        Directory.SetCurrentDirectory(Path.GetDirectoryName(Application.dataPath));
        AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
        string modelPath = Folder + "ForestCrawler.fbx";
        var importer = (ModelImporter)AssetImporter.GetAtPath(modelPath);
        if (!importer) throw new FileNotFoundException("Run the Blender preparation/animation scripts first.");
        importer.animationType = ModelImporterAnimationType.Generic;
        importer.avatarSetup = ModelImporterAvatarSetup.CreateFromThisModel;
        importer.motionNodeName = "Root";
        importer.importAnimation = true; importer.importCameras = false; importer.importLights = false;
        importer.importBlendShapes = false; importer.animationCompression = ModelImporterAnimationCompression.Off;
        importer.isReadable = true; importer.globalScale = 1;
        importer.materialImportMode = ModelImporterMaterialImportMode.None;
        importer.SaveAndReimport();
        var imported = importer.defaultClipAnimations;
        foreach (var clip in imported)
        {
            string name = new[] { "idle", "scream", "charge" }.FirstOrDefault(n => clip.name.EndsWith(n, StringComparison.OrdinalIgnoreCase));
            if (name == null) throw new InvalidOperationException("Unexpected FBX animation: " + clip.name);
            clip.name = name; clip.loopTime = name != "scream"; clip.loopPose = false;
            clip.lockRootRotation = true; clip.lockRootHeightY = true; clip.lockRootPositionXZ = true;
            clip.keepOriginalOrientation = true; clip.keepOriginalPositionY = true; clip.keepOriginalPositionXZ = true;
        }
        importer.clipAnimations = imported; importer.SaveAndReimport();
        var clips = AssetDatabase.LoadAllAssetsAtPath(modelPath).OfType<AnimationClip>().Where(c => !c.name.StartsWith("__")).ToArray();
        foreach (string name in new[] { "idle", "scream", "charge" })
            if (clips.Count(c => c.name == name) != 1) throw new InvalidOperationException("Expected exactly one clip named " + name);
        var controllerPath = Folder + "Crawler.controller";
        AssetDatabase.DeleteAsset(controllerPath);
        var controller = AnimatorController.CreateAnimatorControllerAtPath(controllerPath);
        foreach (string name in new[] { "idle", "scream", "charge" })
        {
            var state = controller.layers[0].stateMachine.AddState(name); state.motion = clips.Single(c => c.name == name); state.writeDefaultValues = true;
            if (name == "idle") controller.layers[0].stateMachine.defaultState = state;
        }
        var body = Material("CrawlerBodyMaterial", "Body.png"); var eyes = Material("CrawlerEyeMaterial", "Eye.png");
        foreach (var file in Directory.GetFiles(Folder, "*.mp3"))
        {
            var audio = (AudioImporter)AssetImporter.GetAtPath(file.Replace('\\', '/'));
            audio.forceToMono = true; audio.loadInBackground = false;
            var sample = audio.defaultSampleSettings; sample.loadType = AudioClipLoadType.DecompressOnLoad;
            sample.compressionFormat = AudioCompressionFormat.Vorbis; sample.quality = .85f;
            audio.defaultSampleSettings = sample; audio.SaveAndReimport();
        }
        BuildCloseup(controller, body, eyes);
        ProcessAudio("sound_scary_heartbeat_single", "heartbeat", true);
        ProcessAudio("sound_scary_chase_very_close", "close", false);
        string manifestCode = "// Generated by CrawlerBuild from decoded source assets.\nnamespace ForestCrawler;\ninternal static class AudioTiming {\n";
        foreach (var pair in new[] { ("Voice", "sound_scary_idle_i_see_you"), ("Scream", "sound_scary_attack_scream"), ("Whisper", "sound_scary_idle_female_whisper"), ("Woo", "sound_scary_idle_woo_woo") })
            manifestCode += "internal const float " + pair.Item1 + " = " + AssetDatabase.LoadAssetAtPath<AudioClip>(Folder + pair.Item2 + ".mp3").length.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "f;\n";
        manifestCode += "internal const float Reveal = " + clips.Single(c => c.name == "scream").length.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "f;\n}\n";
        File.WriteAllText("../src/ForestCrawler/AudioTiming.g.cs", manifestCode);
        var model = AssetDatabase.LoadAssetAtPath<GameObject>(modelPath);
        var root = new GameObject("ForestCrawler");
        var child = (GameObject)PrefabUtility.InstantiatePrefab(model); child.transform.SetParent(root.transform, false);
        foreach (var importedGroup in child.GetComponentsInChildren<LODGroup>(true)) UnityEngine.Object.DestroyImmediate(importedGroup);
        var animator = child.GetComponent<Animator>() ?? child.AddComponent<Animator>();
        animator.runtimeAnimatorController = controller; animator.applyRootMotion = false;
        animator.cullingMode = AnimatorCullingMode.AlwaysAnimate;
        var renderers = root.GetComponentsInChildren<SkinnedMeshRenderer>(true).OrderBy(r => r.name).ToArray();
        if (renderers.Length != 3) throw new InvalidOperationException("Expected 3 LOD meshes.");
        var lods = new LOD[3]; float[] thresholds = { .10f, .045f, .005f };
        foreach (var renderer in renderers)
        {
            if (!renderer.sharedMesh || renderer.sharedMesh.vertexCount == 0) throw new InvalidOperationException("Empty mesh");
            renderer.sharedMaterials = renderer.sharedMesh.subMeshCount == 2 ? new[] { body, eyes } : throw new InvalidOperationException("Expected body and eye submeshes");
            renderer.shadowCastingMode = ShadowCastingMode.On; renderer.receiveShadows = true; renderer.updateWhenOffscreen = true;
            renderer.localBounds = new Bounds(new Vector3(0, 1.2f, 0), new Vector3(4, 4, 4));
            int level = int.Parse(renderer.name.Substring(renderer.name.Length - 1)); lods[level] = new LOD(thresholds[level], new Renderer[] { renderer });
        }
        var group = root.AddComponent<LODGroup>(); group.SetLODs(lods); group.RecalculateBounds();
        foreach (string bone in new[] { "Hips", "Head", "ThighL", "CalfL", "FootL", "ThighR", "CalfR", "FootR" })
            if (!root.GetComponentsInChildren<Transform>().Any(t => t.name == bone)) throw new InvalidOperationException("Missing bone " + bone);
        PrefabUtility.SaveAsPrefabAsset(root, Folder + "ForestCrawler.prefab");
        ValidateAnimations(root, clips);
        UnityEngine.Object.DestroyImmediate(root); AssetDatabase.SaveAssets();
        string output = Path.GetFullPath(Path.Combine(Application.dataPath, "../../artifacts/bundle")); Directory.CreateDirectory(output);
        var runes = (TextureImporter)AssetImporter.GetAtPath(Folder+"Runes.png");
        runes.npotScale=TextureImporterNPOTScale.None; runes.isReadable=true; runes.mipmapEnabled=false; runes.textureCompression=TextureImporterCompression.Uncompressed;
        runes.maxTextureSize=2048; runes.SaveAndReimport();
        var screenShader=AssetDatabase.LoadAssetAtPath<Shader>(Folder+"CrawlerScreen.shader");
        if(!screenShader || ShaderUtil.ShaderHasError(screenShader)) throw new InvalidOperationException("Screen shader compilation failed");
        var paths = Directory.GetFiles(Folder).Where(p => p.EndsWith(".wav") || p.EndsWith(".mp3") || p.EndsWith(".prefab") || p.EndsWith(".shader") || p.EndsWith("rig.json") || p.EndsWith("Runes.png")).Select(p => p.Replace('\\', '/')).ToArray();
        var manifest = BuildPipeline.BuildAssetBundles(output, new[] { new AssetBundleBuild { assetBundleName = "forestcrawler.assets", assetNames = paths } }, BuildAssetBundleOptions.ChunkBasedCompression | BuildAssetBundleOptions.StrictMode, BuildTarget.StandaloneWindows64);
        if (!manifest || !File.Exists(Path.Combine(output, "forestcrawler.assets"))) throw new InvalidOperationException("AssetBundle build failed");
        var bundle = AssetBundle.LoadFromFile(Path.Combine(output, "forestcrawler.assets"));
        if (!bundle || !bundle.LoadAsset<GameObject>("assets/crawler/forestcrawler.prefab")) throw new InvalidOperationException("Built bundle cannot load its prefab");
        File.WriteAllText(Path.Combine(output, "validation.txt"), "Unity " + Application.unityVersion + "\nPrefab, three clips, eight audio assets and facial morph closeup, LODs and rig validated.\n" + string.Join("\n", bundle.GetAllAssetNames()));
        bundle.Unload(true);
        Debug.Log("FORESTCRAWLER_BUILD_OK: " + output);
    }
    private static void BuildCloseup(AnimatorController controller, Material body, Material eyes)
    {
        string path = Folder + "CrawlerCloseup.fbx";
        var importer = (ModelImporter)AssetImporter.GetAtPath(path);
        importer.animationType = ModelImporterAnimationType.Generic;
        importer.avatarSetup = ModelImporterAvatarSetup.CreateFromThisModel;
        importer.motionNodeName = "Root"; importer.importAnimation = false;
        importer.importBlendShapes = true; importer.isReadable = true;
        importer.importCameras = importer.importLights = false;
        importer.materialImportMode = ModelImporterMaterialImportMode.None; importer.SaveAndReimport();
        var obj = (GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(path));
        var animator = obj.GetComponent<Animator>(); animator.runtimeAnimatorController = controller;
        animator.applyRootMotion = false; animator.cullingMode = AnimatorCullingMode.AlwaysAnimate;
        var renderer = obj.GetComponentInChildren<SkinnedMeshRenderer>();
        if (!renderer || renderer.sharedMesh.blendShapeCount != 3) throw new InvalidOperationException("Expected three facial morphs");
        renderer.sharedMaterials = new[] { body, eyes }; renderer.updateWhenOffscreen = true;
        renderer.localBounds = new Bounds(Vector3.up, Vector3.one * 6);
        for (int i = 0; i < 3; i++)
        {
            renderer.SetBlendShapeWeight(i, 100); var mesh = new Mesh(); renderer.BakeMesh(mesh);
            if (mesh.vertices.Any(v => float.IsNaN(v.x) || v.magnitude > 10)) throw new InvalidOperationException("Invalid facial deformation");
            UnityEngine.Object.DestroyImmediate(mesh); renderer.SetBlendShapeWeight(i, 0);
        }
        PrefabUtility.SaveAsPrefabAsset(obj, Folder + "CrawlerCloseup.prefab"); UnityEngine.Object.DestroyImmediate(obj);
    }
    private static void ProcessAudio(string input, string output, bool pulse)
    {
        var source = AssetDatabase.LoadAssetAtPath<AudioClip>(Folder + input + ".mp3"); source.LoadAudioData();
        var data = new float[source.samples * source.channels];
        if (!source.GetData(data, 0)) throw new InvalidOperationException("Unable to decode " + input);
        int start = 0, end = data.Length - 1;
        if (pulse)
        {
            float peak = data.Max(x => Mathf.Abs(x));
            while (start < end && Mathf.Abs(data[start]) < peak * .025f) start++;
            while (end > start && Mathf.Abs(data[end]) < peak * .025f) end--;
        }
        int count = pulse ? Mathf.Min(end - start + 1, Mathf.RoundToInt(source.frequency * .24f)) : data.Length - Mathf.RoundToInt(source.frequency * .12f);
        var samples = new float[count];
        for (int i = 0; i < count; i++)
        {
            // Keep the first physical thump at its original pitch; discard the later thump/reverb.
            float at = pulse ? start + i : i;
            int lo = Mathf.FloorToInt(at); samples[i] = Mathf.Lerp(data[lo], data[Mathf.Min(lo + 1, end)], at - lo);
            if (pulse) samples[i] *= Mathf.Min(1, Mathf.Min(i, count - 1 - i) / (source.frequency * .006f));
        }
        if (!pulse)
        {
            int fade = data.Length - count;
            for (int i = 0; i < fade; i++) samples[i] = Mathf.Lerp(data[count + i], samples[i], i / (float)fade);
        }
        float maximum = samples.Max(x => Mathf.Abs(x));
        if (maximum <= .001f) throw new InvalidOperationException("Silent processed audio");
        for (int i = 0; i < count; i++) samples[i] *= .85f / maximum;
        AssetDatabase.DeleteAsset(Folder + output + ".asset");
        string path = Folder + output + ".wav";
        using (var writer = new BinaryWriter(File.Create(path)))
        {
            writer.Write(System.Text.Encoding.ASCII.GetBytes("RIFF")); writer.Write(36 + count * 2);
            writer.Write(System.Text.Encoding.ASCII.GetBytes("WAVEfmt ")); writer.Write(16); writer.Write((short)1); writer.Write((short)1);
            writer.Write(source.frequency); writer.Write(source.frequency * 2); writer.Write((short)2); writer.Write((short)16);
            writer.Write(System.Text.Encoding.ASCII.GetBytes("data")); writer.Write(count * 2);
            foreach (float value in samples) writer.Write((short)Mathf.RoundToInt(value * 32767));
        }
        AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceSynchronousImport);
        var importer = (AudioImporter)AssetImporter.GetAtPath(path); var settings = importer.defaultSampleSettings;
        settings.compressionFormat = AudioCompressionFormat.PCM; settings.loadType = AudioClipLoadType.DecompressOnLoad;
        importer.defaultSampleSettings = settings; importer.forceToMono = true; importer.SaveAndReimport();
        Debug.Log("Processed " + output + ": " + count / (float)source.frequency + "s peak=.85");
    }
    private static Material Material(string name, string texture)
    {
        string path = Folder + name + ".mat"; var material = AssetDatabase.LoadAssetAtPath<Material>(path);
        var shader=AssetDatabase.LoadAssetAtPath<Shader>(Folder+"ForestCrawlerHorror.shader");
        if(!shader || ShaderUtil.ShaderHasError(shader))
        {
            if(shader) foreach(var message in ShaderUtil.GetShaderMessages(shader)) Debug.LogError(message.message+" at "+message.file+":"+message.line);
            throw new InvalidOperationException("Horror shader compilation failed");
        }
        if (!material) { material = new Material(shader); AssetDatabase.CreateAsset(material, path); }
        material.shader=shader; material.SetFloat("_HorrorStrength",.9f); material.SetFloat("_ChromaticPixels",1.8f); material.SetFloat("_GrainPixels",1.2f);
        material.mainTexture = AssetDatabase.LoadAssetAtPath<Texture2D>(Folder + texture);
        material.SetFloat("_Glossiness", .12f); material.SetFloat("_Metallic", 0);
        if (!material.mainTexture) throw new InvalidOperationException("Missing texture " + texture);
        return material;
    }
    private static void ValidateAnimations(GameObject root, AnimationClip[] clips)
    {
        var model = root.transform.GetChild(0).gameObject;
        foreach (var clip in clips)
        {
            if (clip.length <= 0 || AnimationUtility.GetCurveBindings(clip).Length < 10) throw new InvalidOperationException("Empty animation " + clip.name);
            for (int i = 0; i <= 20; i++)
            {
                clip.SampleAnimation(model, clip.length * i / 20f);
                foreach (var renderer in root.GetComponentsInChildren<SkinnedMeshRenderer>())
                {
                    var mesh = new Mesh(); renderer.BakeMesh(mesh);
                    foreach (var v in mesh.vertices)
                        if (float.IsNaN(v.x) || float.IsInfinity(v.x) || v.magnitude > 10) throw new InvalidOperationException("Invalid deformation in " + clip.name);
                    UnityEngine.Object.DestroyImmediate(mesh);
                }
            }
        }
    }
}
